AUDIO_CHUNK_DURATION = 0.02 # seconds of audio sent to mediassoup each time data is returned

EXTERNAL_SAMPLERATE = 48000     # samplerate in mediasoup
EXTERNAL_N_AUDIO_CHUNK_SAMPLES = int(AUDIO_CHUNK_DURATION*EXTERNAL_SAMPLERATE)
EXTERNAL_N_AUDIO_CHUNK_BYTES = EXTERNAL_N_AUDIO_CHUNK_SAMPLES*2*2 # 16 bits per sample, stereo

INTERNAL_SAMPLERATE = 16000     # samplerate in mediasoup
INTERNAL_N_AUDIO_CHUNK_SAMPLES = int(AUDIO_CHUNK_DURATION*INTERNAL_SAMPLERATE)
INTERNAL_N_AUDIO_CHUNK_BYTES = INTERNAL_N_AUDIO_CHUNK_SAMPLES*2 # 16 bits per sample, mono